//
//  Reference.h
//  CitationTool3
//
//  Created by Thomas Gray on 20/09/2015.
//  Copyright (c) 2015 Thomas Gray. All rights reserved.
//

#import <Foundation/Foundation.h>
#import "Year.h"
#import "Name.h"
#import "Citation.h"

@class Citation;

#define AUTHOR @"author"
#define ADDRESS @"address"
#define ANNOTE @"annote"
#define BOOKTITLE @"booktitle"
#define CHAPTER @"chapter"
#define CROSSREF @"crossref"
#define EDITION @"edition"
#define EDITOR @"editor"
#define HOWPUBLISHED @"howpublished"
#define INSTITUTION @"institution"
#define JOURNAL @"journal"
#define MONTH @"month"
#define NOTE @"note"
#define NUMBER @"number"
#define ORGANIZATION @"organization"
#define PAGES @"pages"
#define PUBLISHER @"publisher"
#define SCHOOL @"school"
#define SERIES @"series"
#define TITLE @"title"
#define VOLUME @"volume"
#define YEAR @"year"

#define ARTICLE @"article"
#define BOOK @"book"
#define BOOKLET @"booklet"
#define CONFERENCE @"conference"
#define INBOOK @"inbook"
#define INCOLLECTION @"incollection"
#define INPROCEEDINGS @"inproceedings"
#define MANUAL @"manual"
#define MASTERTHESIS @"masterthesis"
#define MISC @"misc"
#define PHDTHESIS @"phdthesis"
#define PROCEEDINGS @"proceedings"
#define TECHREPORT @"techreport"
#define UNPUBLISHED @"unpublished"


@interface Reference : NSObject{
    NSMutableCharacterSet * emptyChars;
    NSCharacterSet * braceChars;
    NSString* bibTexString;
}

# pragma mark -BibTeX fields

@property NSString* key;
@property (nonatomic) NSString* type;

@property (readonly) NSMutableDictionary<NSString*, NSString*>* fields;
@property (readonly) NSMutableDictionary<NSString*, NSString*>* texFields;
@property (readonly) NSMutableArray* keys;

#pragma mark -Custom Fields

@property NSMutableArray<Name*>* authorArray; //name array
@property NSMutableArray<Name*>* editorArray; //name array
@property NSInteger yearInt;
@property unichar yearModifier; //not set initially, but may be saved for future reference
@property BOOL keyAutoGenerated;

#pragma mark -Methods

-(instancetype)initWithBibEntry:(NSString*)bibString;

-(void)getDataFromBib:(NSString*)bibString;
-(NSString*)getTexString;

-(NSString*)addFieldValueNullable:(NSString*)val forKeyNullable:(NSString*)key isTexFormat:(BOOL)tex;
-(void)modifyField:(NSString*)newval forKey:(NSString*)ky isTexFormat:(BOOL)tex;

-(BOOL)matchesCitation:(Citation*)cite;
-(BOOL)isEqualToReference:(Reference*)ref;

-(NSString*)toStringTypeTitle;

-(NSAttributedString*)getReferenceStub;
-(NSString*)getAuthorsAndYear;
-(NSAttributedString*)getReferenceCompleteString;

//-(NSString*)getAuthorStringWithAmpersand:(BOOL)withAmp;
-(NSString*)getAuthorStringWithFinalDelimiter:(NSString*)delimit;

+(NSInteger)getIndexOfFirst:(unichar)c inString:(NSString*)str;
+(NSMutableArray*)makeArrayOfNames:(NSString*)names;



+(NSMutableArray*)getReferencesFromFile:(NSString*)path;
+(NSMutableArray*)getReferenceStringsFromWhole:(NSString*)wholeString;

-(NSComparisonResult)compare:(Reference*)ref byFields:(NSArray<NSString*>*)compareKeys;
+(void)sortArray:(NSMutableArray<Reference*>*)ref withFields:(NSArray<NSString*>*)keys;

#pragma mark Static Fields (and Type) Retrievers

+(NSArray *)getEntryTypes;
+(NSArray*) getEstablishedFields;


+(NSArray*)articleFields;
+(NSArray*)bookFields;
+(NSArray*)bookletFields;
+(NSArray*)conferenceFields;
+(NSArray*)inbookFields;
+(NSArray*)incollectionFields;
+(NSArray*)inproceedingsFields;
+(NSArray*)manualFields;
+(NSArray*)masterthesisFields;
+(NSArray*)miscFields;
+(NSArray*)phdthesisFields;
+(NSArray*)proceedingsFields;
+(NSArray*)techreportFields;
+(NSArray*)unpublishedFields;

+(NSArray*)getCorrespondingPrincipleFields:(NSString*)type;


@end
